version: "3.7"

services:
  web:
    env_file:
      - .env

    # Build from Dockerfile in current directory
    build: .

    environment:
      # Server settings
      NODE_ENV: "development"

      # External server address
      SERVER_HOST_URL: "http://localhost:3000/"

      # Local server settings
      SERVER_PORT: 3000

      LOGGING_LEVEL: "debug"
      LOGGING_ACCESS_LOG: "true"

      # API runs on host
      API_URI: "http://host.docker.internal:3001/api/kursinfo"

      # API runs in ref
      KOPPS_URI: "https://api-r.referens.sys.kth.se/api/kopps/v2/?defaultTimeout=60000"
      KURSPLAN_API_URI: "https://api-r.referens.sys.kth.se/api/kursplan?defaultTimeout=60000"

    ports:
      - 3000:3000
