# Github Actions workflow for Evolene CI
# More information:
# - Github Actions workflows: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
# - Evolene: https://github.com/kth/evolene
name: Evolene CI

on:
  push:
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Evolene:
    name: Continuous Integration
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run Evolene CI pipeline steps
        shell: bash
        env:
          # You can put here NON-SECRET environmental variables here alongside
          # variables that configure Evolene

          # To add secrets, go to Settings > Secrets > Repository Secrets
          # and add a variable called "EVOLENE_TEST_SECRETS" with the secrets
          # as "key=value" pairs.
          # Read more: https://github.com/kth/evolene

          # Environmental variables for Evolene:
          # BUILD_INFORMATION_OUTPUT_FILE: "/config/version.js"  # Create a file with the build information
          # BRANCHES_SAVE_STARTING_WITH: "origin/"          # Builds non main or master branches.
          # BRANCHES_TAG_AS_MAIN: "True"                    # Do not add branch names to build artifacts
          SLACK_CHANNELS: "#team-kursinfo-build"            # List of Slack channels for user information
          # SKIP_DRY_RUN: True                              # Skip "dry run" step

        run: |
          ${{ secrets.EVOLENE_RUN_COMMAND }}
